POST http://localhost:8080/events
Content-Type: application/json

{
  "name": "Test event 2",
  "description": "Another test event",
  "location": "123 Main Street, Cityville",
  "dateTime": "2024-03-20T18:00:00Z"
}