POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3MTMyMTU5MDIsInVzZXJJZCI6MX0.PVv-hQ77CMz1ll3EK_MCa3ayDLkJJt4oGVrdp-Zj0rY

{
  "name": "Test event",
  "description": "Another test event",
  "location": "123 Main Street, Cityville",
  "dateTime": "2024-03-20T18:00:00Z"
}