DELETE http://localhost:8080/events/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzEzMjEyNTM0LCJ1c2VySWQiOjJ9.i1SmIAZDc_e6-cYL-aTBJUcEl2TOXiSt3U8gqaNJEFc