PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name" : "Updated test event",
    "description": "A test event",
    "location" : "Test location (Updated)!",
    "dateTime": "2024-03-20T18:00:00Z",
    "userId" : 1
}